name: Docker Image CI

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:
         docker build . --file Dockerfile --tag jubnzv1/cppcheck:$(date +%s) && docker push jubnzv1/cppcheck1
