name: Docker Image CI

on:
  schedule:
    - cron:  '0 0 * * *'
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jubnzv1/cppcheck
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
